#!/usr/bin/env node
/*
 * Regenerates the root index.html.
 *
 * Every top-level folder holding an index.html becomes a row. The row's text
 * comes from that page's own <title> and <meta name="description">, so adding a
 * page to the site is the only step — nothing here needs editing.
 *
 * Run with `node build-index.js`. CI runs it on every push (.github/workflows).
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SKIP = new Set(['node_modules', '.github', '.git']);

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const tagOf = (html, re) => {
  const m = html.match(re);
  return m ? m[1].trim() : '';
};

const pages = fs.readdirSync(ROOT, { withFileTypes: true })
  .filter(d => d.isDirectory() && !d.name.startsWith('.') && !SKIP.has(d.name))
  .filter(d => fs.existsSync(path.join(ROOT, d.name, 'index.html')))
  .map(d => {
    const html = fs.readFileSync(path.join(ROOT, d.name, 'index.html'), 'utf8');
    return {
      slug: d.name,
      title: tagOf(html, /<title>([^<]*)<\/title>/i) || d.name,
      desc: tagOf(html, /<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i)
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const rows = pages.length
  ? pages.map(p => `      <a class="row" href="/${p.slug}/">
        <div class="txt">
          <code>/${esc(p.slug)}/</code>
          <div class="name">${esc(p.title)}</div>
${p.desc ? `          <div class="desc">${esc(p.desc)}</div>\n` : ''}        </div>
        <div class="arw" aria-hidden="true">&rarr;</div>
      </a>`).join('\n')
  : `      <p class="empty">No pages yet — add a folder with an index.html.</p>`;

const out = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#0b0d10">
<meta name="color-scheme" content="dark">
<meta name="robots" content="noindex">
<meta name="description" content="Index of pages">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<title>karmidd.github.io</title>
<!-- Generated by build-index.js — edits here are overwritten on the next push. -->
<style>
:root{
  --bg:#0b0d10;--line:#242b33;--text:#e8edf2;
  --dim:#8b959f;--dim2:#5f6874;--acc:#a8e05f;
  color-scheme:dark;
}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html{background:var(--bg);min-height:100%}
body{
  margin:0;min-height:100dvh;color:var(--text);
  font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  background:
    radial-gradient(680px 420px at 50% 42%, rgba(168,224,95,.085), transparent 66%),
    var(--bg);
  background-attachment:fixed;
  display:flex;align-items:center;justify-content:center;
  padding:40px 20px calc(40px + env(safe-area-inset-bottom));
}
.wrap{width:100%;max-width:440px}

.brand{display:flex;align-items:center;gap:10px}
.dot{
  width:9px;height:9px;border-radius:50%;background:var(--acc);flex:none;
  box-shadow:0 0 16px rgba(168,224,95,.7);
}
h1{font-size:25px;font-weight:680;letter-spacing:-.035em;margin:0;line-height:1}
.tag{
  font:12px/1.4 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  color:var(--dim2);margin:7px 0 24px;padding-left:19px;
}

a.row{
  display:grid;grid-template-columns:1fr auto;align-items:center;gap:16px;
  text-decoration:none;color:inherit;
  background:linear-gradient(180deg,#171c22,#12161b);
  border:1px solid var(--line);border-radius:15px;
  padding:16px 18px;margin-bottom:10px;
  transition:border-color .16s,transform .16s,box-shadow .16s;
}
a.row:hover{
  border-color:#425c2b;transform:translateY(-2px);
  box-shadow:0 10px 26px rgba(0,0,0,.5);
}
a.row:active{transform:translateY(0)}
.txt{min-width:0}
.row code{
  font:11.5px/1.3 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  color:var(--acc);letter-spacing:.02em;
}
.name{font-size:16px;font-weight:650;letter-spacing:-.015em;margin-top:4px}
.desc{font-size:13px;color:var(--dim);margin-top:2px}
.arw{color:var(--dim2);font-size:17px;flex:none;transition:transform .16s,color .16s}
a.row:hover .arw{color:var(--acc);transform:translateX(3px)}

.empty{
  font-size:13.5px;color:var(--dim2);margin:0;padding:22px 18px;
  border:1px dashed var(--line);border-radius:15px;
}
.foot{font-size:11.5px;color:var(--dim2);margin:16px 0 0;padding-left:2px}
</style>
</head>
<body>
  <div class="wrap">
    <div class="brand"><span class="dot"></span><h1>karmidd</h1></div>
    <p class="tag">karmidd.github.io</p>
${rows}
    <p class="foot">${pages.length} page${pages.length === 1 ? '' : 's'}</p>
  </div>
</body>
</html>
`;

// --- exercise photo manifest -------------------------------------------
// Lists the photos that actually exist in training/img/, so the training page
// only requests images it will get, instead of 404ing on every missing one.
const IMG_DIR = path.join(ROOT, 'training', 'img');
const photos = {};
if (fs.existsSync(IMG_DIR)) {
  for (const f of fs.readdirSync(IMG_DIR)) {
    const m = f.match(/^(.+)\.(jpg|jpeg|png|webp)$/i);
    if (m) photos[m[1].toLowerCase()] = f;
  }
}
fs.writeFileSync(
  path.join(IMG_DIR, 'photos.js'),
  '/* Generated by build-index.js — do not edit. */\nwindow.EX_PHOTOS = ' +
  JSON.stringify(photos, null, 2) + ';\n'
);
console.log(`photos.js: ${Object.keys(photos).length} photo(s)`);

fs.writeFileSync(path.join(ROOT, 'index.html'), out);
console.log(`index.html: ${pages.length} page(s) — ${pages.map(p => '/' + p.slug + '/').join(' ') || 'none'}`);
