#!/usr/bin/env node
/*
 * Regenerates the root index.html.
 *
 * Every top-level folder holding an index.html becomes a row. The row's text
 * comes from that page's own <title> and <meta name="description">, so adding a
 * page to the site is the only step — nothing here needs editing.
 *
 * Run with `node build-index.js`. CI runs it on every push (.github/workflows).
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SKIP = new Set(['node_modules', '.github', '.git']);

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const tagOf = (html, re) => {
  const m = html.match(re);
  return m ? m[1].trim() : '';
};

const pages = fs.readdirSync(ROOT, { withFileTypes: true })
  .filter(d => d.isDirectory() && !d.name.startsWith('.') && !SKIP.has(d.name))
  .filter(d => fs.existsSync(path.join(ROOT, d.name, 'index.html')))
  .map(d => {
    const html = fs.readFileSync(path.join(ROOT, d.name, 'index.html'), 'utf8');
    return {
      slug: d.name,
      title: tagOf(html, /<title>([^<]*)<\/title>/i) || d.name,
      desc: tagOf(html, /<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i)
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const rows = pages.length
  ? pages.map(p => `      <a class="row" href="/${p.slug}/">
        <code>/${esc(p.slug)}/</code>
        <span>${esc(p.desc || p.title)}</span>
      </a>`).join('\n')
  : `      <p class="empty">No pages yet. Add a folder with an index.html.</p>`;

const out = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#0b0d10">
<meta name="robots" content="noindex">
<meta name="description" content="Index of pages">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<title>karmidd.github.io</title>
<!-- Generated by build-index.js — edits here are overwritten on the next push. -->
<style>
:root{--bg:#0b0d10;--panel:#14181d;--line:#242b33;--text:#e8edf2;--dim:#8b959f;--dim2:#5f6874;--acc:#a8e05f}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
body{
  margin:0;background:var(--bg);color:var(--text);padding:44px 20px;
  font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
}
.wrap{max-width:560px;margin:0 auto}
h1{
  font-size:13px;font-weight:650;margin:0 0 2px;letter-spacing:.01em;color:var(--dim);
  display:flex;align-items:center;gap:8px;
}
h1 span{width:6px;height:6px;border-radius:50%;background:var(--acc);flex:none}
.count{font-size:12px;color:var(--dim2);margin:0 0 18px;padding-left:14px}
.list{border-top:1px solid var(--line)}
a.row{
  display:flex;align-items:baseline;gap:14px;text-decoration:none;color:inherit;
  padding:14px 4px;border-bottom:1px solid var(--line);transition:background .12s,padding .12s;
}
a.row:hover{background:#12171b;padding-left:10px}
a.row code{
  font:13.5px/1.4 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  color:var(--acc);flex:none;
}
a.row span{font-size:13.5px;color:var(--dim);flex:1;min-width:0}
.empty{font-size:13.5px;color:var(--dim2);padding:16px 4px;border-bottom:1px solid var(--line)}
@media (max-width:430px){
  a.row{flex-direction:column;gap:3px}
  a.row span{font-size:13px}
}
</style>
</head>
<body>
  <div class="wrap">
    <h1><span></span>karmidd.github.io</h1>
    <p class="count">${pages.length} page${pages.length === 1 ? '' : 's'}</p>
    <div class="list">
${rows}
    </div>
  </div>
</body>
</html>
`;

fs.writeFileSync(path.join(ROOT, 'index.html'), out);
console.log(`index.html: ${pages.length} page(s) — ${pages.map(p => '/' + p.slug + '/').join(' ') || 'none'}`);
